// import './short.js';
// import './literal.js';
// import './computed.js';
// import './is.js';
// import './assign.js';
// import './proto.js';
// import './getOwnProperty.js';
// import './hasInstance.js';
// import './toPrimitive.js';
import './toStringTag.js';
